security:
    # Hash des mots de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # User provider (ici en mémoire, à adapter plus tard si tu utilises l'entité User)
    providers:
        users_in_memory:
            memory: ~

    firewalls:
        dev:
            # Toujours autoriser les outils de dev et assets
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false

        main:
            lazy: true
            provider: users_in_memory
            # custom_authenticator: App\Security\LoginFormAuthenticator
            # (supprimé car la classe n'existe plus)

    access_control:
    # Exemple si tu veux protéger plus tard certaines URLs
    # - { path: ^/admin, roles: ROLE_ADMIN }
    # - { path: ^/profile, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
